### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Keep-Simple** [Keep-Simple/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by sicc-nick** [comment]
- I'm the hottest redheaded guy, you've ever met. As soon as I became president of the USA, ~~I will gain even more money and power~~ America will be great again.

**Comment by Keep-Simple** [comment]
Don't make me cry, pls

**Comment by Keep-Simple** [comment]
<h2>Resume</h2>

<p>&mdash; I'm the hottest redheaded guy, you've ever met. As soon as I <strong>became president</strong> of the USA, <del>I'm gonna gain even more power and money</del> <strong>America will be great again.</strong> Vote for me, if your favorite word is solidarity. Eh wait, vote for me anyways, cause I'm the <strong>One</strong>.</p>

**Comment by Keep-Simple-2** [comment]
youoy
