### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Keep-Simple** [Keep-Simple/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні

**Comment by sicc-nick** [comment]
**Donald Trump**

- www.twitter.com/realDonaldTrump

- www.instagram.com/realDonaldTrump

- www.facebook.com/DonaldTrump

**Comment by Keep-Simple-2** [comment]
ypypy
