### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Keep-Simple** [Keep-Simple/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме

**Comment by sicc-nick** [comment]
**Achievements and work**
 
**1968**
First steps in father's dev company

**1971**
Got main chair in the company

**1978**
Build Grand Hyatt Hotel

**1980**
First bricks in the Trump Tower skyscraper

**1983**
New Jersey Generals purchase (football team)

**1985**
Private club in Palm Beach

**1988**
Acquired the Plaza Hotel for $407m, that would be sold in 1995 

**1994**
Refurbished the Gulf and Western Building on Columbus Circle

**2001**
Completed Trump World Tower

**2005**
Trump University

**2009**
Republican again

**2016**
Won election race

**2017**
45th president of America

**Comment by Keep-Simple-2** [comment]
asdf
