### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Keep-Simple** [Keep-Simple/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by sicc-nick** [comment]
**SKILLS** (◉‿◉)

TWITTING, BLAMING, BUILDING WALLS, TALK ABOUT GREATNESS

**CHARACTER** (ㆆ _ ㆆ)

AMBITIOUS, CONFIDENT, CARELESS, SINGLE-MINDED

**LIKES** ☜(⌒▽⌒)☞

COKE, TAXES, PATRIOTS, GOLD, BANKS

**DISLIKES** •`_´•

CHINA, LESBIANS, JEWS, ARABS, MEXICANS, TAX-FREE

**Comment by Keep-Simple-2** [comment]
yooy
